common: &common
  adapter: postgresql
  encoding: unicode
  username: brian
  password:
  pool: 5

development:
  <<: *common
  database: vip_development

test:
  <<: *common
  database: vip_test

production:
  <<: *common
  database: vip_production
