common: &common
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: phenom
  pool: 5

development:
  <<: *common
  database: vern_development

test:
  <<: *common
  database: vern_test

production:
  <<: *common
  database: vern_production
